name: Java Test with Maven

on:
  schedule:
    - cron:  '0 3,6,9,12,15,18,21 * * *'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Thundra Foresight JS Instrumentation
        uses: actions/upload-artifact@v2
        with:
          name: test-result-junit
          path: target/surefire-reports
            
      #- name: Thundra Maven Test Instrumentation
      #  uses: thundra-io/thundra-maven-test-action@v1
      #  with:
      #    apikey: ${{ secrets.THUNDRA_API_KEY }}
      #    project_id: ${{ secrets.THUNDRA_PROJECT_ID }}
      #    command: mvn test
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.me/v1
          THUNDRA_AGENT_REPORT_UPLOAD_REST_URL: https://upload.thundra.me
