name: Java Test with Maven

on:
  schedule:
    - cron:  '0 3,6,9,12,15,18,21 * * *'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Thundra Maven Test Instrumentation
        uses: thundra-io/thundra-maven-test-action@v1
        with:
         # apikey: ${{ secrets.THUNDRA_API_KEY }}
         # project_id: ${{ secrets.THUNDRA_PROJECT_ID }}
          apikey: 35ec4777-fbe3-408e-bd08-68ad75ed698b
          project_id: 3ede3a9e-5625-42f5-a476-420574e4d432
          command: mvn test
