name: Build with skip tests

on:
  schedule:
    - cron:  '0 3,6,9,12,15,18,21 * * *'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        cache: maven
    - name: Build 
      run: mvn package -Dmaven.test.skip
